Style/Documentation:
  Enabled: false

AllCops:
  SuggestExtensions: false
  Exclude:
    - playground.rb
    - 'spec/**/*'
    - Brewfile
    - 'bin/**/*'
    - db/schema.rb
    - db/migrate/**/*.rb
